# Enable or disable all cops. By default, all cops are enabled.
# You can disable a specific cop by setting it to `false`.
# You can also enable a disabled cop by setting it to `true`.

AllCops:
  DisabledByDefault: false
  Include:
    - '**/*.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes # Prefer single-quoted strings

Layout/LineLength:
  Max: 200 # Set your preferred line length

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*' # Exclude block length checks in spec files

