require 'active_record'
require 'enumerize'
require_relative 'user'
require_relative 'question'
require_relative 'choice'
require_relative 'difficulty'
require_relative 'trivia'
require_relative 'true_false'
require_relative 'autocomplete'
require_relative 'question_answer'
require_relative 'answer'

